### ISSUE TITLE
Neural Voices

### ISSUE THREAD

**Issue by christianeuropa** [svrooij/node-sonos-tts-polly#10]
Hello Stefan,

thank you very much for your work. I would like to know whether it is possible to use the neural voices as well? Maybe with a syntax? I like the neural voices better than the standard.

Christian

**Comment by svrooij** [comment]
Hi @christianeuropa it's for sure possible to make it possible to load the neural voices. You are probably using it in [sonos2mqtt](https://svrooij.io/sonos2mqtt/), right?

That means this should not only be changed in this app but also in [node-sonos-ts](https://svrooij.io/node-sonos-ts/), related code can be found [here](https://github.com/svrooij/node-sonos-ts/blob/master/src/helpers/tts-helper.ts)

Time is somewhat limited right now, I will be accepting a PR (and thus welcoming the first contributor) for this.

**Comment by svrooij** [comment]
Check out the new version ([1.0.8](https://github.com/svrooij/node-sonos-tts-polly/releases/tag/v1.0.8)) or use this image `docker pull ghcr.io/svrooij/node-sonos-tts-polly:1.0.8`

**Comment by christianeuropa** [comment]
Thanks for the new version.
I just wanted to test the new version in docker. But unfortunately it doesn't really work. My log shows:
/usr/local/bin/sonos-tts-polly: line 1: use strict: not found
/usr/local/bin/sonos-tts-polly: line 2: syntax error: unexpected "("

**Comment by christianeuropa** [comment]
1.0.9 works. Thanks very much.

**Comment by svrooij** [comment]
This new functionality isn't yet implemented in the node-sonos-ts library, but I'll try that some where in the next weeks.

In the mean time, there is a one-time sponsor option on my [sponsor profile](https://github.com/sponsors/svrooij).
