### ISSUE TITLE
provide docker image for linux/arm?

### ISSUE THREAD

**Issue by Kosta-Github** [svrooij/node-sonos-tts-polly#2]
would you mind to also provide "linux/arm" docker images as a multi-arch image?
similar to `sonos2mqtt`...

**Comment by svrooij** [comment]
Great idea, why didn't I do that before?

I'm slowly converting all my smarthome apps to typescript but that is a slow proces.

**Comment by svrooij** [comment]
The new image took a little bit more work, but it's ready now.

https://hub.docker.com/r/svrooij/sonos-tts-polly/tags

<img width="911" alt="Screenshot 2020-04-17 at 17 14 38" src="https://user-images.githubusercontent.com/1292510/79584639-f594a800-80ce-11ea-97fb-6ce51f517bb0.png">


https://github.com/sponsors/svrooij

**Comment by Kosta-Github** [comment]
cool 👍 thx
