### ISSUE TITLE
Selection of a special voice is possible e.g. Marlene, Hans, or Vicky.

### ISSUE THREAD

**Issue by papaloewe** [svrooij/node-sonos-tts-polly#3]
Hello Stefan, 
great work, thank you very much.
Maybe I missed it in your documentation, but is it possible to select a single voice from polly?

Thomas

**Comment by svrooij** [comment]
The code that matches the correct voice, does so by matching gender. I didn’t know there where any languages that have multiple voices in the same gender defined. The code can be adjusted to also support a name (next to gender).

Are the in the same language code?

https://github.com/svrooij/node-sonos-tts-polly/blob/master/src/server.ts#L117-L126

**Comment by papaloewe** [comment]
Yes, there are some: e.g. in german "Marlene" and "Vicky", both are female. ;-)

**Comment by svrooij** [comment]
The latest sonos2mqtt [beta](https://github.com/svrooij/node-sonos-ts/releases/tag/v2.0.9-beta.2) includes support for selecting the language by name. 

Fixed at the same time as this [issue](https://github.com/svrooij/node-sonos-ts/issues/54)
